# Homework 1:
1- Build a Keras Model for linear regression (check: https://keras.io/activations/). Use Boston Housing Dataset to train and test your model

2- Build a Keras Model for logistic regression. Use diabetes.csv to train and test

Comments:

1- Build the simplest model for linear regression with Keras and compare your model performance with from sklearn.linear_model import LinearRegression

2- Build the simplest model for logistic regression with Keras and compare your model performance with from sklearn.linear_model import LogisticRegression

3- Add more complexity to your models in (1) and (2) and compare with previous results

Got Help from Nathan Pal on this one!

# 2- Build a Keras Model for logistic regression

In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix


import keras
from keras.models import Sequential
from keras.layers import Dense

In [31]:
diabetes = pd.read_csv('./diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [32]:
X = diabetes.loc[:, 'Pregnancies':'Age']
y = pd.DataFrame(data=diabetes['Outcome'], columns=['Outcome'])
y.head()

Outcome
0        1
1        0
2        1
3        0
4        1

In [33]:
#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25, random_state= 0)

In [34]:
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


In [35]:
#Create Classifier mdoel
classifier = Sequential()
#add I/O
classifier.add(Dense(activation='sigmoid', input_dim=8, units=1, kernel_initializer='uniform'))
#compile model
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [36]:
#fit the model 
classifier.fit(X_train, y_train, batch_size=1, epochs=100)

Epoch 1/100
576/576 [==============================] - 1s 2ms/step - loss: 0.6309 - acc: 0.7396
Epoch 2/100
576/576 [==============================] - 1s 1ms/step - loss: 0.5680 - acc: 0.7535
Epoch 3/100
576/576 [==============================] - 1s 1ms/step - loss: 0.5369 - acc: 0.7622
Epoch 4/100
576/576 [==============================] - 1s 1ms/step - loss: 0.5195 - acc: 0.7587
Epoch 5/100
576/576 [==============================] - 1s 1ms/step - loss: 0.5086 - acc: 0.7639
Epoch 6/100
576/576 [==============================] - 1s 1ms/step - loss: 0.5017 - acc: 0.7691
Epoch 7/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4969 - acc: 0.7656
Epoch 8/100
576/576 [==============================] - 1s 2ms/step - loss: 0.4937 - acc: 0.7778
Epoch 9/100
576/576 [==============================] - 1s 2ms/step - loss: 0.4912 - acc: 0.7691
Epoch 10/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4896 - acc: 0.7691
Epoch 11/100
576/576 [=================

576/576 [==============================] - 1s 1ms/step - loss: 0.4843 - acc: 0.7639
Epoch 85/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4842 - acc: 0.7656
Epoch 86/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4844 - acc: 0.7639
Epoch 87/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4842 - acc: 0.7674
Epoch 88/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4842 - acc: 0.7656
Epoch 89/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4843 - acc: 0.7656
Epoch 90/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4845 - acc: 0.7622
Epoch 91/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4844 - acc: 0.7674
Epoch 92/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4843 - acc: 0.7691
Epoch 93/100
576/576 [==============================] - 1s 1ms/step - loss: 0.4844 - acc: 0.7656
Epoch 94/100
576/576 [=====================

In [37]:
#predict test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred> .5)
y_pred

array([[ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [

In [38]:
# make a confusion matrix
cm = confusion_matrix(y_test, y_pred)

In [39]:
cm

array([[118,  12],
       [ 26,  36]])

# Classic ML algorythem for Logistic Regression

In [40]:
lr = LogisticRegression(random_state=0, solver='liblinear', multi_class='ovr').fit(X_train, y_train)

/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [41]:
y_pred = lr.predict(X_test)


In [42]:
cm2 = confusion_matrix(y_test, y_pred)


In [43]:
cm2

array([[118,  12],
       [ 26,  36]])